#!/bin/bash

function pause(){
read -p "$*"
}

cd system/client

echo 'running echo 'Test message' >> outbound/00004'
echo 'Test message for end to end test sent from annalistic to anthropomorphologically!' >> outbound/00004
pause 'Press [Enter] key to continue...'
echo ''

echo 'running bin/getcert annalistic -p thickets_pimping'
bin/getcert annalistic -p thickets_pimping
pause 'Press [Enter] key to continue...'
echo ''

echo 'running bin/sendmsg outbound/00004 anthropomorphologically'
bin/sendmsg outbound/00004 anthropomorphologically
pause 'Press [Enter] key to continue...'
echo ''

echo 'running bin/getcert anthropomorphologically -p likelihoods_hoarsely'
bin/getcert anthropomorphologically -p likelihoods_hoarsely
pause 'Press [Enter] key to continue...'
echo ''

echo 'running bin/recvmsg'
bin/recvmsg
pause 'Press [Enter] key to continue...'
echo ''

cd ../../
