#!/bin/bash

function pause(){
read -p "$*"
}

cd system/client

echo 'getcert- valid test:'
echo 'running bin/getcert addleness -p Cardin_pwns'
bin/getcert addleness -p Cardin_pwns
pause 'Press [Enter] key to continue...'
echo ''

echo 'getcert- buffer overflow in username test:'
echo 'running bin/getcert invaliduserrnamethatismuchtoolongandcouldbeapotentialoverflowattempt'
bin/getcert invaliduserrnamethatismuchtoolongandcouldbeapotentialoverflowattempt
pause 'Press [Enter] key to continue...'
echo ''

echo 'getcert- invalid username test:'
echo 'running bin/getcert invalidusername'
bin/getcert invalidusername
pause 'Press [Enter] key to continue...'
echo ''

echo 'getcert- invalid password test:'
echo 'running bin/getcert addleness -p invalidpassword'
bin/getcert addleness -p invalidpassword
pause 'Press [Enter] key to continue...'
echo ''

echo 'getcert- buffer overflow in password test:'
echo 'running bin/getcert addleness -p invalidpasswordthatismuchtoolongandcouldbeapotentialoverflowattempt'
bin/getcert addleness -p invalidpasswordthatismuchtoolongandcouldbeapotentialoverflowattempt 
pause 'Press [Enter] key to continue...'
echo ''

cd ../../
