#!/bin/bash

function pause(){
read -p "$*"
}

cd system/client


echo 'recvmsg- valid test:'
echo 'running bin/recvmsg'
bin/recvmsg
pause 'Press [Enter] key to continue...'
echo ''

echo 'recvmsg- no messages test:'
echo 'running bin/getcert analects -p pass'
bin/getcert analects -p pass
echo 'running bin/recvmsg'
bin/recvmsg
pause 'Press [Enter] key to continue...'
echo ''

cd ../../
