#!/bin/bash

function pause(){
read -p "$*"
}

cd system/client


echo 'running echo 'Test message' >> outbound/00003'
echo 'Test message' >> outbound/00003
echo ''

echo 'recvmsg- valid test:'
echo 'running bin/recvmsg addleness'
bin/recvmsg addleness
pause 'Press [Enter] key to continue...'
echo ''

echo 'recvmsg- no messages test:'
echo 'running bin/getcert analects -p pass'
bin/getcerts analects -p pass
echo 'running bin/recvmsg analects'
bin/recvmsg analects
pause 'Press [Enter] key to continue...'
echo ''

echo 'recvmsg- not logged in user test:'
echo 'running bin/recvmsg addleness'
bin/recvmsg addleness
pause 'Press [Enter] key to continue...'
echo ''

echo 'recvmsg- invalid username test:'
echo 'running bin/recvmsg invalidusername'
bin/recvmsg invalidusername
pause 'Press [Enter] key to continue...'
echo ''

cd ../../
