#!/bin/bash

function pause(){
read -p "$*"
}

echo '============================'
echo '|      getcert tests       |'
echo '============================'
pause 'Press [Enter] key to continue...'
echo ''

tests/getcert-tests

echo '============================'
echo '|      changepw tests      |'
echo '============================'
pause 'Press [Enter] key to continue...'
echo ''

tests/changepw-tests

echo '============================'
echo '|      sendmsg tests       |'
echo '============================'
pause 'Press [Enter] key to continue...'
echo ''

tests/sendmsg-tests

echo '============================'
echo '|      recvmsg tests       |'
echo '============================'
pause 'Press [Enter] key to continue...'
echo ''

tests/recvmsg-tests

echo '============================'
echo '|     end to end tests     |'
echo '============================'
pause 'Press [Enter] key to continue...'
echo ''

tests/endtoend-tests

echo 'See TestSteps for manual test cases'
